### ISSUE TITLE
database columns potentially out of sync with foreman 3.4

### ISSUE THREAD

**Issue by madelaney** [theforeman/puppetdb_foreman#73]
When I attempted to setup a new Foreman(`3.4.0`) instance with puppetdb_foreman (`v5.0.0-4`). The database migration and seeding fail with a few missing columns:
* description
* full_name
* encrypted

```
2022-09-09 13:15:03 -0400 /Stage[main]/Foreman::Database/Foreman::Rake[db:seed]/Exec[foreman-rake-db:seed]/returns (notice): rake aborted!
2022-09-09 13:15:03 -0400 /Stage[main]/Foreman::Database/Foreman::Rake[db:seed]/Exec[foreman-rake-db:seed]/returns (notice): ActiveModel::UnknownAttributeError: unknown attribute 'descrip
tion' for Setting::Puppetdb.
2022-09-09 13:15:03 -0400 /Stage[main]/Foreman::Database/Foreman::Rake[db:seed]/Exec[foreman-rake-db:seed]/returns (notice): /usr/share/foreman/vendor/ruby/2.7.0/gems/activemodel-6.1.6.1/
lib/active_model/attribute_assignment.rb:51:in `_assign_attribute'
2022-09-09 13:15:03 -0400 /Stage[main]/Foreman::Database/Foreman::Rake[db:seed]/Exec[foreman-rake-db:seed]/returns (notice): /usr/share/foreman/vendor/ruby/2.7.0/gems/activerecord-6.1.6.1
/lib/active_record/attribute_assignment.rb:21:in `block in _assign_attributes'
2022-09-09 13:15:03 -0400 /Stage[main]/Foreman::Database/Foreman::Rake[db:seed]/Exec[foreman-rake-db:seed]/returns (notice): /usr/share/foreman/vendor/ruby/2.7.0/gems/activerecord-6.1.6.1
/lib/active_record/attribute_assignment.rb:13:in `each'
2022-09-09 13:15:03 -0400 /Stage[main]/Foreman::Database/Foreman::Rake[db:seed]/Exec[foreman-rake-db:seed]/returns (notice): /usr/share/foreman/vendor/ruby/2.7.0/gems/activerecord-6.1.6.1
/lib/active_record/attribute_assignment.rb:13:in `_assign_attributes'
2022-09-09 13:15:03 -0400 /Stage[main]/Foreman::Database/Foreman::Rake[db:seed]/Exec[foreman-rake-db:seed]/returns (notice): /usr/share/foreman/vendor/ruby/2.7.0/gems/activemodel-6.1.6.1/
lib/active_model/attribute_assignment.rb:34:in `assign_attributes'
2022-09-09 13:15:03 -0400 /Stage[main]/Foreman::Database/Foreman::Rake[db:seed]/Exec[foreman-rake-db:seed]/returns (notice): /usr/share/foreman/vendor/ruby/2.7.0/gems/activerecord-6.1.6.1
/lib/active_record/core.rb:518:in `initialize'
2022-09-09 13:15:03 -0400 /Stage[main]/Foreman::Database/Foreman::Rake[db:seed]/Exec[foreman-rake-db:seed]/returns (notice): /usr/share/foreman/vendor/ruby/2.7.0/gems/activerecord-6.1.6.1
/lib/active_record/inheritance.rb:72:in `new'
2022-09-09 13:15:03 -0400 /Stage[main]/Foreman::Database/Foreman::Rake[db:seed]/Exec[foreman-rake-db:seed]/returns (notice): /usr/share/foreman/vendor/ruby/2.7.0/gems/activerecord-6.1.6.1
/lib/active_record/inheritance.rb:72:in `new'
2022-09-09 13:15:03 -0400 /Stage[main]/Foreman::Database/Foreman::Rake[db:seed]/Exec[foreman-rake-db:seed]/returns (notice): /usr/share/foreman/vendor/ruby/2.7.0/gems/activerecord-6.1.6.1
/lib/active_record/persistence.rb:54:in `create!'
2022-09-09 13:15:03 -0400 /Stage[main]/Foreman::Database/Foreman::Rake[db:seed]/Exec[foreman-rake-db:seed]/returns (notice): /usr/share/foreman/vendor/ruby/2.7.0/gems/puppetdb_foreman-5.0
.0/app/models/setting/puppetdb.rb:40:in `block (2 levels) in load_defaults'
2022-09-09 13:15:03 -0400 /Stage[main]/Foreman::Database/Foreman::Rake[db:seed]/Exec[foreman-rake-db:seed]/returns (notice): /usr/share/foreman/vendor/ruby/2.7.0/gems/puppetdb_foreman-5.0
.0/app/models/setting/puppetdb.rb:40:in `each'
2022-09-09 13:15:03 -0400 /Stage[main]/Foreman::Database/Foreman::Rake[db:seed]/Exec[foreman-rake-db:seed]/returns (notice): /usr/share/foreman/vendor/ruby/2.7.0/gems/puppetdb_foreman-5.0
.0/app/models/setting/puppetdb.rb:40:in `block in load_defaults'
```

These fields appear to be removed in [20220124174632_drop_setting_fields.rb](https://github.com/theforeman/foreman/blob/develop/db/migrate/20220124174632_drop_setting_fields.rb).

**Comment by alexdga** [comment]
Same problem here, can't upgrade to foreman 3.4 because of database migrations errors.

**Comment by demonstrator** [comment]
I have the same issue. Is there an ETA when this will be fixed as it's currently a blocker for foreman 3.4?

**Comment by timogoebel** [comment]
@kamils-iRonin provides a fix in https://github.com/theforeman/puppetdb_foreman/pull/74, do you guys mind testing it and giving feedback if this works? We can then merge it once ci passes and tests confirm the patch works and release a new version.
